theme: jekyll-theme-minimal
title: Ramkumar
description: Experienced Copywriter with a demonstrated history of working in the broadcast media industry. Skilled in Scriptwriting, Advertising, Digital Marketing, and Voice Acting.